version: '3.6'

volumes:
  dbdata:

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5433:5432 # Mapped to 5433 in case Postgres is already running locally on 5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data_collector